/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 arm.gltf --transform
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-honey-robotic-arm-c50671f2a8e74de2a2e687103fdc93ab
Title: Black Honey - Robotic Arm
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./public/img/arm-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.21}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="roboarm001_low_0" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm002_low_1" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm003_low_2" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm004_low_3" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm005_low_4" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm006_low_5" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm007_low_6" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm008_low_7" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm009_low_8" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm010_low_9" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm011_low_10" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm012_low_11" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm013_low_12" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm014_low_13" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm015_low_14" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm016_low_15" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm017_low_16" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm018_low_17" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm019_low_18" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm020_low_19" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm021_low_20" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm022_low_21" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm023_low_22" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm024_low_23" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm025_low_24" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm026_low_25" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm027_low_26" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm028_low_27" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.robo_arm} />
              </group>
              <group name="roboarm_low_28" position={[0.22, 0.55, 0.31]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.robo_arm} />
              </group>
              <group name="robot_base002_low_31" position={[0.09, 0.78, 0.04]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base003_low_32" position={[0.12, 0.65, 0.15]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base004_low_33" position={[0.08, 0.78, 0.03]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base005_low_34" position={[0.13, 0.67, 0.15]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base006_low_35" position={[0.15, 0.56, 0.25]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base008_low_36" position={[0.44, 0.69, -0.34]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base009_low_37" position={[0.09, 0.26, 0.07]} rotation={[-Math.PI, 0.66, -Math.PI]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base018_low_38" rotation={[-Math.PI, 0.66, -Math.PI]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base011_low_39" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base012_low_40" position={[0.48, 2.04, -0.61]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base013_low_41" position={[0.42, 0.69, -0.36]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base014_low_42" position={[0.9, 0.52, -1.16]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base015_low_43" position={[0.48, 2.04, -0.61]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base016_low_44" position={[0.11, 0.26, 0.08]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base017_low_45" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base020_low_46" position={[0.9, 0.52, -1.16]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base019_low_47" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base021_low_48" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base022_low_49" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base023_low_50" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base_low_51" position={[0.9, 0.52, -1.16]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base024_low_52" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base025_low_53" rotation={[-Math.PI, 0.66, -Math.PI]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base026_low_54" position={[0.9, 0.52, -1.16]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base027_low_55" position={[0.48, 2.04, -0.61]} rotation={[-0.65, -0.55, 2.76]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base028_low_56" position={[0.9, 0.52, -1.16]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base029_low_57" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base030_low_58" position={[-0.12, 0.1, 0.16]} rotation={[2.13, 0.39, -2.6]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base031_low_59" rotation={[-Math.PI, 0.66, -Math.PI]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base007_low_61" position={[0.15, 0.56, 0.25]} rotation={[-2.43, 0.53, 2.73]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base033_low_62" position={[0.62, 0.69, -0.2]} rotation={[2.13, 0.39, -2.6]} scale={1.08}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base035_low_63" position={[0.9, 0.52, -1.16]} rotation={[-1.71, 0.11, 2.49]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base010_low_29" position={[0, 0.07, 0]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base001_low_30">
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.robot_base} />
              </group>
              <group name="robot_base032_low_60">
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.robot_base} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/arm-transformed.glb')
