/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 world.gltf --transform
Author: murilo.kleine (https://sketchfab.com/murilo.kleine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-terra-downloadable-model-30fd7e9c4e6946ddb6fcae7a97b2b0d4
Title: Earth | Terra - Downloadable model
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./public/img/world-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[0,100,1]}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} >
          <group name="Root">
            <group name="EARTH">
              <mesh name="EARTH_0" geometry={nodes.EARTH_0.geometry} material={materials['Material.001']} />
            </group>
            <group name="Armature">
              <primitive object={nodes.Armature_rootJoint} />
              <skinnedMesh name="ATM_0" geometry={nodes.ATM_0.geometry} material={materials['Material.002']} skeleton={nodes.ATM_0.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/world-transformed.glb')
